apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: 339712873615.dkr.ecr.ap-south-1.amazonaws.com/mani/todo-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_DATABASE
          value: "todo_management"
        - name: MYSQL_USER
          value: "demo"
        - name: MYSQL_PASSWORD
          value: "Veera0987"
        - name: MYSQL_ROOT_PASSWORD
          value: "Veera0987"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: todo-app
